language: php
sudo: false

env:
  global:
    - secure: "Eqab5Hz31l7Pk+doXD8qypFIg+2pRoV1YzavUxPNa8+LJ7fuOSzzTulYl/MJy256V+TXGx9oeam4s+BnVuRDPZLCUlPPmKp43kZO0lEG4JvDAriPhOztFB9nWc51Uey6z+l8BLT3U6YP+yA1c7Ao8cURdrdTvTc3FpotBOmjfD7hEtuNH0UL2H+YN8CQBA9JiY9/5yZhcH8eCGr+ubCQy567fFgxqrKpjorfyBs2/pSHkv5avVT9CVgZ7n0YZoebcVh8Km2m5yiwPO58Gxz9vlFyCZ16mFCRBoQdVouCXU4V2JY3rSrZy5KinRnCREcRNn9G9m1pcGqnC6XU01pLlXPN9WCPm3xyzaXvok0MDhNJBmFCWza05xdbFg3vrQ7ODziCF8AhClZGaA3NHuLgfyV02cz1UTq3oEVj7xXCh4PfzDHbwS4N9j+oigwm+TAKQPv2XQ4HQDgFJDfZa+KFcoCygK8UDkzXIZKZQpmPvX14Qmwj//HzPosXHWhOWOIWwY2OoTBsGz1zH3U2U5P8/JwObOyTP0GjVr9vyX+ssO2baJxJRxAx6BqGRWtol5MRJ2DYJkUDQQSxHg/46XrtMiVx3eg73qPvI2/r/aFP01AUojRhy9+RYKiHl6i1mDf+6opAnnkFSFEa/elovqfGKIXrIzszoIYX8nC9hGdaSlg="
    - secure: "PDXD/fdB/44o9VGx0/FqbqzKiLoxALt7ADXtGlNiT4HHKcYdQo/r5MpF0nsdPXb6jcJX+bycGSYhyMunyYvn/C5kCYoFBE6aGGV7zN6QKpfZJVyoJQfb9Ha7hXT8lzrNj1UYjb6ujJRv8m3gL7D0+dOw4LKiemTemSx6pASuIGUw/3Ov1hJD1G4Ip+NV2HqP182WjTItZlimN1WQsSqLNZdNhBO6JTvCl2jvM4kmM16ESRkaEOatNFxfq58zNPwEMOI2SXfr8W96okq0Fa6pjAu/foDaYwrodE0d/zbJgt2Ybu7i3956EhvgthTyJsc1w9AUnJDOLfeBLsKvlmGalrjwN6lMaX83a+pfFB0RDcFYhR+Q8KU5/mdk/c5BxNgZWPsjgn6vz1Ob66qaao83H1C4Bobr1soUGiwnW2Ahr058bhs2w6ubtuc89u7GxNqGQi+ZmgimMjzqtQJWfq2cyJD6ZPkMR7AHJ2s8Gly31HIIs7tECSBBN2Rdp+Q+3AEnVdgBhC81GumcQZKuoYhkQE/jNfZcTRv/3pGuIF3boZ9aU4EMpP5TelXlgB8KQtcDve8+GGXbV/9+VdVM2Iw4uccGGYkC9S37JmrLrROVQlkzy9ykHdl7CuYV+RDMm/xjd3G118OT5w69h3JBvUFm4ZyjsEUz++RlBNcr10ug8Ws="
    - secure: "coO6wZwE7moYcITt2sKdGEz06fVtCRIuXiWfvNOFYjwaVESwsjhxWAoqsTy2Ga306mSNd2Mf3X+Q+nox0dxgkg1Ppia5J51HxzpqdtGeAtj/OowIV4rwfUuACufMmF8hcEIVkQesxd8NLOLT2kKNuy1vDV+TBYJ7Zws0O1Eblk7THJ8Af9QrNVDG8PFJWb3Wh8TnqVwRH2Q1sEdy5sdmaN8BmWqe0puXT2F++0j7SyMhgtHDGV/IMtex1JolgUa4nsr4KC225seRdAJK18Llk4KjQNGO+y8Z+s2pNI77ZLJG26fNz/pFn65BwhSpYEwQuJSjVCmkAdkHxDeSBr8npIXlLOmBUhPdXQbOpW1la0W7j4eaPv6AxPtNpFJ1E9vyoRYbdNtsOoL8raY5QE5d6vLZBaon8qLRhU+FcjJdiRvMEBB4JWUTqhkkP8RjYC8yGsNKTwHR7G9lcsUS4K+bNkL8yvgjGlloY8nOQ+39t2N00B0GkWUQA6zAK4xWCo44xIQLYQx5acyNoweGLoOwcJ/5s6j2BzmPFW3CbdAKTR6MkoIqE9pPV4dyn36OBdFgA6J6qMWptB9uZ74KiQ5ZjQTMVtWN/HYCBXskgvodHNCi7eztnt9Ek64qUipIETTr1O5Eu1cQQdfsyfQk71TBbu4FDfqxqQEAFsqKw8iy5N0="

php:
  - 5.6
  - 7.0
  - hhvm

install:
  # Install Composer.
  - composer install

script:
  # Run PHPUnit tests.
  - ./vendor/bin/phpunit -c ./phpunit.xml.dist --coverage-text
